<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BA-000311972" name="com.telus.wnp.tests.WLSC_169220_WNP_REG_AnHYKoodoSMGConfirm" tests="1" failures="1" timestamp="09 Feb 2022 13:51:25 GMT" time="36.158" errors="0">
  <testcase name="testMethod_AnHYKoodoSMGConfirm" time="36.158" classname="com.telus.wnp.tests.WLSC_169220_WNP_REG_AnHYKoodoSMGConfirm">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Subscriber status is not as expected expected [active] but found [cancelled]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Subscriber status is not as expected expected [active] but found [cancelled]
at com.test.ui.actions.Validate.assertEquals(Validate.java:1228)
at com.telus.wnp.steps.SmartDesktopSearchPageSteps.verifySubscriberStatusFromSD(SmartDesktopSearchPageSteps.java:69)
at com.telus.wnp.tests.WLSC_169220_WNP_REG_AnHYKoodoSMGConfirm.testMethod_AnHYKoodoSMGConfirm(WLSC_169220_WNP_REG_AnHYKoodoSMGConfirm.java:115)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: Subscriber status is not as expected expected [active] but found [cancelled]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.test.ui.actions.Validate.assertEquals(Validate.java:1224)
... 27 more
]]>
    </failure>
  </testcase> <!-- testMethod_AnHYKoodoSMGConfirm -->
</testsuite> <!-- com.telus.wnp.tests.WLSC_169220_WNP_REG_AnHYKoodoSMGConfirm -->
